### ISSUE TITLE
Gazetteer-based string matcher NER

### ISSUE THREAD

**Issue by keighrim** [brandeis-llc/dtriac-pipeline#12]
Take some *expert knowledge* (e.g. from this wiki page: https://en.wikipedia.org/wiki/List_of_United_States%27_nuclear_weapons_tests) and make it into a simple NER.

**Comment by marcverhagen** [comment]
I have some code in the technologies stuff for this and will see whether it would scale.

**Comment by marcverhagen** [comment]
The code to do the lookup for the previous demo is not efficient since it relies on string matching of a list of phrases. This was timed at 0.01s for a 30K file when using a technology list of 100 terms. This will not scale but it may work just well enough for now.

Also use Michael's topic annotations as expert knowledge.

**Comment by marcverhagen** [comment]
Instead of Michael's annotations, use Wikipedia categories under the nuclear physics category (see [wiki categories](https://en.wikipedia.org/wiki/Special:CategoryTree?target=Category%3ANuclear+physics&mode=categories&namespaces=&title=Special%3ACategoryTree)).

**Comment by keighrim** [comment]
Code at  brandeis-llc/dtriac-wikification#6 revealed that `Nucluear physics` has 333,934 subcategories and had found more than 8 million pages after running for more than 20 hrs. (It was still running, but I decided to break it). 

I think we should take [the subset from `Nuclear technology`](https://raw.githubusercontent.com/brandeis-llc/dtriac-wikification/09452ab51210677d4df936db0909ebb3fe635d84/subset/Nuclear_technology.txt) not only because of the size is more manageable (55214 pages), but also in the 0.3 m subcategories there are a lot of irrelevant noises. Here's a random sample (n=20) from that. 

---
```
Buildings and structures in Montgomery County, Virginia
Multinational companies headquartered in Singapore
Israel transport stubs
Norwegian artistic gymnast stubs
Paleontology in the Philippines
Chinese Filipino organizations
Egypt–Guyana relations
2012 in sports in Texas
20th-century economic history
Sony Professional
Indonesian articles requiring attention
Football clubs in Santa Catarina (state)
Vanuatuan people by religion
Neogene Venezuela
1977 in Punjabi cinema
Japanese otolaryngologists
Uganda and the Commonwealth of Nations
Houses in Arlington, Massachusetts
Geography of Park County, Montana
American expatriates in Norway
```

**Comment by keighrim** [comment]
I think this done via dfc9440ff78ece9e9c71b5a80cea237e22bf757e and dc2c8a42f52a3b52a2ec22604401c78d09153d7b. One thing we're still getting is the `John J. Kingman Road` (and its variations).

**Comment by marcverhagen** [comment]
Yes, that was done, but as far as I am concerned it is not looking good enough.

I do not see `John J. Kingman Road` anywhere, can you point me to it?

**Comment by keighrim** [comment]
I'm seeing `JOHN J.` and `John J. Kingman` in the author cloud. No Kingmans in the location cloud though (that's good!).

**Comment by marcverhagen** [comment]
Ah, you mean without the "Road", yes, I am aware of that one, fairly easy fix that is on my list.

**Comment by keighrim** [comment]
I think it's okay have a couple of those in the person/author cloud. Gives some sense of reality, as James mentioned.

**Comment by marcverhagen** [comment]
Yeah, but there is plenty if reality remaining after obvious cleanup. My favorite is "Marina del Rey" as a person.
