### ISSUE TITLE
corenlp in pipeline for 19d

### ISSUE THREAD

**Issue by keighrim** [brandeis-llc/dtriac-pipeline#14]
We'd like to have corenlp annotations on the `19d` dataset. Specifically, we'll run sentence splitter and NER.

**Comment by keighrim** [comment]
By the way, according to the [official documentstion](https://stanfordnlp.github.io/CoreNLP/ner.html), corenlp NER is a 12-way tagger. 

> this annotator recognizes named (PERSON, LOCATION, ORGANIZATION, MISC), numerical (MONEY, NUMBER, ORDINAL, PERCENT), and temporal (DATE, TIME, DURATION, SET) entities (12 classes).)

**Comment by keighrim** [comment]
Splitter is done and lif files are available as `/data/dtriac/dtriac-19d/all-processed/spl/<doc_id>/<doc_id>.spl.lif`. 
POS and NER is running now, and ETAs are \~2.5 hrs and \~11 hrs, respectively. They'll be placed in the `/data/dtriac/dtriac-19d/all-processed/` in the same way as `spl` once they're done.

**Comment by keighrim** [comment]
POS and NER have finished, and ~placed~ (actually) symlinked to the `/data/dtriac/dtriac-19d/all-processed` directory, like splitter results.

**Comment by keighrim** [comment]
All objectives are done, closing the issue.

**Comment by pustejovsky** [comment]
How do the results look?
