### ISSUE TITLE
Script to create JSON files for Elastic Search

### ISSUE THREAD

**Issue by marcverhagen** [brandeis-llc/dtriac-pipeline#17]
Can be based on the [create_index_docs](https://github.com/brandeis-llc/dtriac-534/blob/master/scripts/create_index_docs.py) in https://github.com/brandeis-llc/dtriac-534, but needs more changes than I originally thought.

**Comment by keighrim** [comment]
I think this was initially done via 660f579284912c62501bc89188c7cb4d596a91ef. I think we can close this.

**Comment by marcverhagen** [comment]
Yeah, it will still need to be updated but what updates we need is pretty obvious so we don't need this issue anymore.
